---
# Source: kafdrop/templates/01-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: kafdrop-secret
  labels:
    app: kafdrop
    group: amqp
    release: kafdrop
data:
---
# Source: kafdrop/templates/02-configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafdrop-cm
  labels:
    app: kafdrop
    group: amqp
    release: kafdrop
data:
  KAFKA_BROKERCONNECT: "kafka-broker-0.kafka-broker-headless.bepsa.svc.cluster.local:9092"
  SERVER_SERVLET_CONTEXTPATH: "/"
  JVM_OPTS: "-Xms128M -Xmx256M"
---
# Source: kafdrop/templates/04-service.yml
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  labels:
    app: kafdrop
    group: amqp
    release: kafdrop
  annotations:
spec:
  type: ClusterIP
  selector:
    app: kafdrop
  ports:
    - port: 80
      targetPort: 9000
---
# Source: kafdrop/templates/03-statefulset.yml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafdrop-sts
  labels:
    app: kafdrop
    group: amqp
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: kafdrop
  serviceName: kafdrop-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: kafdrop
        group: amqp
        release: kafdrop
      annotations:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - kafdrop
              topologyKey: topology.kubernetes.io/zone
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: kafdrop
          image: "obsidiandynamics/kafdrop:3.28.0-SNAPSHOT"
          imagePullPolicy: IfNotPresent
#          resources:
#            limits:
#              cpu: 500m
#              memory: 512Mi
#            requests:
#              cpu: 200m
#              memory: 256Mi
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: kafdrop-cm
            - secretRef:
                name: kafdrop-secret

